services:
  gitea:
    image: docker.gitea.com/gitea:1.24.6
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea-postgre
      - GITEA__database__USER=gitea-postgre
      - GITEA__database__PASSWD=gitea-postgre
    restart: always
    networks:
      - application
    volumes:
      - ./data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "222:22"
      - "3000:3000"
    depends_on:
      - db
  db:
    image: docker.io/library/postgres:14
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=gitea-postgre
      - POSTGRES_PASSWORD=gitea-postgre
      - POSTGRES_DB=gitea-postgre
    networks:
      - application
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  gitea-runner:
    image: gitea/act_runner:latest
    container_name: gitea-runner
    restart: always
    networks:
      - application
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/runner-data:/data
    environment:
      # docker 网络过于垃圾，只能用容器名替代了。
      - GITEA_INSTANCE_URL=http://gitea:3000
      - GITEA_RUNNER_REGISTRATION_TOKEN=psXWrwAIlKVxiRneqY4DBCCKdGGRjdsMI5x1Z2rM
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        act_runner register --no-interactive \
          --instance "$$GITEA_INSTANCE_URL" \
          --token "$$GITEA_RUNNER_REGISTRATION_TOKEN" \
          --name "runner-1" \
          --labels "docker:host" \
          && act_runner daemon
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      AUTH_TYPE: LOGIN_FORM
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: admin
    ports:
      - "58080:8080"
    restart: unless-stopped
    networks:
      - application

networks:
  application:
    external: true
